//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoNotificador
    {
        public long id { get; set; }
        public string vchCorreo { get; set; }
        public string vchPassword { get; set; }
        public string vchPuerto { get; set; }
        public string vchHost { get; set; }
    }
}
