//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionesEnviadas
    {
        public long id { get; set; }
        public long id_correo { get; set; }
        public long id_proceso { get; set; }
        public System.DateTime datFechaEnviado { get; set; }
    
        public virtual CorreosDestinatarios CorreosDestinatarios { get; set; }
        public virtual Procesos Procesos { get; set; }
    }
}
