//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procesos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Procesos()
        {
            this.NotificacionesEnviadas = new HashSet<NotificacionesEnviadas>();
        }
    
        public long id { get; set; }
        public string vchTiempoEspera { get; set; }
        public string vchNombreProceso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionesEnviadas> NotificacionesEnviadas { get; set; }
    }
}
